main: main.cpp datatypes.cpp fileUtils.cpp renderchars.cpp menubar.cpp
	clang++ -O3 -mwindows -std=c++2a -o BetterCode main.cpp datatypes.cpp fileUtils.cpp renderchars.cpp menubar.cpp -m64 -I"/usr/include/c++/7.5.0/immer-0.6.2/" -lstdc++fs -lSDL2main -lSDL2
