main: main.cpp datatypes.cpp fileUtils.cpp renderchars.cpp menubar.cpp
	clang++-10 -g -O3 -std=c++20 -o BetterCode main.cpp datatypes.cpp fileUtils.cpp renderchars.cpp menubar.cpp -m64 -I"/usr/include/c++/10/immer-0.6.2/" -lSDL2main -lSDL2
